#!/bin/bash

setup() {
  i:venv
  i:npm_install
}

serve() {
  .venv/bin/python engine.py serve --host 0.0.0.0
}

build() {
  .venv/bin/python engine.py build
  lightningcss --browserslist --bundle --minify build/assets/styles/main.css -o build/assets/styles/main.min.css
  rm build/assets/styles/main.css build/assets/styles/base.css build/assets/styles/bookmarks.css build/assets/styles/blog.css build/assets/styles/fonts.css build/assets/styles/projects.css build/assets/styles/skeleton.css
  prettier --write --config .prettierrc --ignore-path /dev/null "build/**/*.{css,js,xml,html}"
}

deploy() {
  build
  g:deploy
}
